export const StreamData = [
    {
        type: 'Cricket',
        tournament: 'Cricket World Cup',
        date: '2024-11-10',
        time: '14:00',
        team1: 'Team A',
        team2: 'Team B',
    },
    {
        type: 'Cricket',
        tournament: 'Indian Premier League (IPL)',
        date: '2024-02-02',
        time: '20:00',
        team1: 'Mumbai Indians',
        team2: 'Chennai Super Kings',
    },
    {
        type: 'Cricket',
        tournament: 'Big Bash League (BBL)',
        date: '2024-03-15',
        time: '18:30',
        team1: 'Sydney Sixers',
        team2: 'Melbourne Stars',
    },
    {
        type: 'Cricket',
        tournament: 'T20 World Cup',
        date: '2024-09-20',
        time: '16:45',
        team1: 'Team X',
        team2: 'Team Y',
    },
    {
        type: 'Cricket',
        tournament: 'Ashes Series',
        date: '2024-12-01',
        time: '11:00',
        team1: 'England',
        team2: 'Australia',
    },
    {
        type: 'Cricket',
        tournament: 'Asia Cup',
        date: '2024-06-05',
        time: '15:30',
        team1: 'India',
        team2: 'Pakistan',
    },
    {
        type: 'Cricket',
        tournament: 'Test Match',
        date: '2024-04-18',
        time: '09:30',
        team1: 'South Africa',
        team2: 'New Zealand',
    },
    {
        type: 'Tennis',
        tournament: 'Wimbledon',
        date: '2024-07-01',
        time: '14:30',
        team1: 'Roger Federer',
        team2: 'Novak Djokovic',
    },
    {
        type: 'Tennis',
        tournament: 'US Open',
        date: '2024-09-08',
        time: '16:00',
        team1: 'Serena Williams',
        team2: 'Rafael Nadal',
    },
    {
        type: 'Tennis',
        tournament: 'French Open',
        date: '2024-05-26',
        time: '12:00',
        team1: 'Simona Halep',
        team2: 'Dominic Thiem',
    },
    {
        type: 'Tennis',
        tournament: 'Australian Open',
        date: '2024-01-20',
        time: '11:00',
        team1: 'Ashleigh Barty',
        team2: 'Novak Djokovic',
    },
    {
        type: 'Tennis',
        tournament: 'ATP Finals',
        date: '2024-11-10',
        time: '17:30',
        team1: 'Top Seed A',
        team2: 'Top Seed B',
    },
    {
        type: 'Tennis',
        tournament: 'Davis Cup',
        date: '2024-04-02',
        time: '13:15',
        team1: 'Country X',
        team2: 'Country Y',
    },
    {
        type: 'Soccer',
        tournament: 'FIFA World Cup',
        date: '2026-06-08',
        time: '18:00',
        team1: 'Brazil',
        team2: 'Germany',
    },
    {
        type: 'Soccer',
        tournament: 'UEFA Champions League',
        date: '2025-05-29',
        time: '20:45',
        team1: 'Real Madrid',
        team2: 'Manchester City',
    },
    {
        type: 'Soccer',
        tournament: 'Premier League',
        date: '2024-12-15',
        time: '16:30',
        team1: 'Liverpool',
        team2: 'Chelsea',
    },
    {
        type: 'Soccer',
        tournament: 'La Liga',
        date: '2025-02-23',
        time: '21:00',
        team1: 'Barcelona',
        team2: 'Real Madrid',
    },
    {
        type: 'Soccer',
        tournament: 'Bundesliga',
        date: '2024-11-05',
        time: '14:30',
        team1: 'Bayern Munich',
        team2: 'Borussia Dortmund',
    },
    {
        type: 'Soccer',
        tournament: 'Serie A',
        date: '2024-10-18',
        time: '19:45',
        team1: 'Juventus',
        team2: 'AC Milan',
    },
    {
        type: 'Soccer',
        tournament: 'Copa America',
        date: '2024-07-10',
        time: '17:00',
        team1: 'Argentina',
        team2: 'Brazil',
    },
    {
        type: 'Soccer',
        tournament: 'AFC Asian Cup',
        date: '2024-01-30',
        time: '15:30',
        team1: 'Japan',
        team2: 'South Korea',
    },
    {
        type: 'Boxing',
        tournament: 'Olympic Boxing Tournament',
        date: '2024-08-15',
        time: '12:45',
        team1: 'Boxer A',
        team2: 'Boxer B',
    },
    {
        type: 'Boxing',
        tournament: 'World Boxing Super Series',
        date: '2024-04-05',
        time: '21:15',
        team1: 'Super Middleweight A',
        team2: 'Super Middleweight B',
    },
    {
        type: 'Boxing',
        tournament: 'WBC World Championship',
        date: '2024-11-20',
        time: '22:30',
        team1: 'Champion X',
        team2: 'Challenger Y',
    },
    {
        type: 'Boxing',
        tournament: 'IBF World Championship',
        date: '2025-03-12',
        time: '19:00',
        team1: 'Titleholder P',
        team2: 'Contender Q',
    },
    {
        type: 'Boxing',
        tournament: 'WBO World Championship',
        date: '2024-06-30',
        time: '18:45',
        team1: 'Champ Z',
        team2: 'Challenger W',
    },
    {
        type: 'Hockey',
        tournament: 'IIHF World Championship',
        date: '2024-05-15',
        time: '16:30',
        team1: 'Canada',
        team2: 'USA',
    },
    {
        type: 'Hockey',
        tournament: 'Stanley Cup Playoffs',
        date: '2024-04-20',
        time: '20:15',
        team1: 'Team C',
        team2: 'Team D',
    },
    {
        type: 'Hockey',
        tournament: 'Olympic Ice Hockey Tournament',
        date: '2026-02-08',
        time: '13:45',
        team1: 'Sweden',
        team2: 'Russia',
    },
    {
        type: 'Hockey',
        tournament: 'Champions Hockey League',
        date: '2025-11-30',
        time: '19:30',
        team1: 'Club E',
        team2: 'Club F',
    },
    // Add more dummy data as needed
];